// Code generated by MockGen. DO NOT EDIT.
// Source: dispatcher.go

// Package kim is a generated GoMock package.
package kim

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pkt "github.com/klintcheng/kim/wire/pkt"
)

// MockDispather is a mock of Dispather interface.
type MockDispather struct {
	ctrl     *gomock.Controller
	recorder *MockDispatherMockRecorder
}

// MockDispatherMockRecorder is the mock recorder for MockDispather.
type MockDispatherMockRecorder struct {
	mock *MockDispather
}

// NewMockDispather creates a new mock instance.
func NewMockDispather(ctrl *gomock.Controller) *MockDispather {
	mock := &MockDispather{ctrl: ctrl}
	mock.recorder = &MockDispatherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispather) EXPECT() *MockDispatherMockRecorder {
	return m.recorder
}

// Push mocks base method.
func (m *MockDispather) Push(gateway string, channels []string, p *pkt.LogicPkt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", gateway, channels, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockDispatherMockRecorder) Push(gateway, channels, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockDispather)(nil).Push), gateway, channels, p)
}
